### PR TITLE
fix #139: swap not returning true on key-map change

### LINKED ISSUE #139: :repl/set-key-map is not working

### PR DESCRIPTION
**Pull request by i-blis**
I've been looking into the issue #139 and it happened that the problem comes ultimately from your implementation of swap which failed to return true on successful change. Once spotted, the fix is a tiny one.

I tested but manually... :

```clojure
rebel-dev.main=> (:key-map @api/*line-reader*)   
:emacs  
rebel-dev.main=> :repl/set-key-map :viins  
Changed key map to :viins  
rebel-dev.main=> (:key-map @api/*line-reader*)  
:viins  
```

### CODE REVIEW

File: rebel-readline/src/rebel_readline/jline_api.clj [hunk 1]
```diff
@@ -268,7 +268,8 @@ If you are using `lein` you may need to use `lein trampoline`."
       (deref [] (.getVariable this service-variable-name))
       ;; TODO implement all swaps??
       (swap  [f & args] (swap* this f args))
-      (reset [a] (.setVariable this service-variable-name a)))))
+      (reset [a] (do (.setVariable this service-variable-name a)
+                     true)))))
```
Comment (bhauman) [inline rebel-readline/src/rebel_readline/jline_api.clj]: I'm going to change this to return `a` instead of true

**Comment by bhauman** [comment]
And thanks for working on this!
